# Generated by Django 5.2.8 on 2025-12-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faltas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
