# Generated by Django 6.0 on 2025-12-05 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_falta', models.DateField()),
                ('es_tardanza', models.BooleanField(default=False)),
                ('fecha_limite_excusa', models.DateField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Excusa',
            fields=[
                ('falta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asistencia_api.falta')),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('documento_adjunto', models.FileField(upload_to='excusas/')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada'), ('V', 'Vencida por Plazo')], default='P', max_length=1)),
                ('instructor_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excusas_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
