# Generated by Django 5.2.8 on 2025-12-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faltas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excusa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='excusas/')),
                ('fecha_presentacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('cargada', 'Cargada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='cargada', max_length=20)),
                ('razon_rechazo', models.TextField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('falta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excusa', to='faltas.falta')),
            ],
        ),
    ]
