# Generated by Django 5.2.8 on 2025-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('dias_habiles_para_excusa', models.IntegerField(default=3)),
                ('tipos_documento_permitidos', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
